use super::*;

/// `"bun"` module / `Bun.*` globals shim pack (issue #6560, Tier 0 of
/// Bun-app support — driver: opencode).
///
/// Runtime implementations live in perry-runtime `bun_compat`, except the
/// TCP/Unix socket facade in perry-ext-net and the url aliases, which reuse
/// the `node:url` FFI directly.
/// `Bun.stdin` / `Bun.stdout` / `Bun.stderr` are property reads (handled by
/// `js_native_module_property_by_name`), not rows here.
pub(crate) const BUN_ROWS: &[NativeModSig] = &[
    NativeModSig {
        module: "bun:jsc",
        has_receiver: false,
        method: "heapStats",
        class_filter: None,
        runtime: "js_bun_jsc_heap_stats",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "spawn",
        class_filter: None,
        runtime: "js_bun_spawn",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "Terminal",
        class_filter: None,
        runtime: "js_bun_terminal_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "Transpiler",
        class_filter: None,
        runtime: "js_bun_transpiler_new",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "listen",
        class_filter: None,
        runtime: "js_bun_tcp_listen",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "serve",
        class_filter: None,
        // The listener lives in perry-ext-http and returns a native server
        // handle, reusing the same event-loop pump as node:http.
        runtime: "js_bun_serve",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "build",
        class_filter: None,
        runtime: "js_bun_build",
        args: &[NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "connect",
        class_filter: None,
        runtime: "js_bun_tcp_connect",
        args: &[NA_F64],
        ret: NR_PROMISE,
    },
    NativeModSig {
        module: "bun",
        has_receiver: true,
        method: "transformSync",
        class_filter: Some("Transpiler"),
        runtime: "js_bun_transpiler_transform_sync",
        args: &[NA_STR, NA_STR],
        ret: NR_STR,
    },
    NativeModSig {
        module: "bun",
        has_receiver: true,
        method: "transform",
        class_filter: Some("Transpiler"),
        runtime: "js_bun_transpiler_transform",
        args: &[NA_STR, NA_STR],
        ret: NR_PROMISE,
    },
    NativeModSig {
        module: "bun",
        has_receiver: true,
        method: "scanImports",
        class_filter: Some("Transpiler"),
        runtime: "js_bun_transpiler_scan_imports",
        args: &[NA_STR],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "bun",
        has_receiver: true,
        method: "scan",
        class_filter: Some("Transpiler"),
        runtime: "js_bun_transpiler_scan",
        args: &[NA_STR],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "SQL",
        class_filter: None,
        runtime: "js_bun_sql_new",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "stringWidth",
        class_filter: None,
        runtime: "js_bun_string_width",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "hash",
        class_filter: None,
        // Returns an already-NaN-boxed BigInt value (not a raw
        // BigIntHeader pointer), so NR_F64 passes it through.
        runtime: "js_bun_hash",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "deepEquals",
        class_filter: None,
        runtime: "js_bun_deep_equals",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "stripANSI",
        class_filter: None,
        runtime: "js_bun_strip_ansi",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "wrapAnsi",
        class_filter: None,
        runtime: "js_bun_wrap_ansi",
        args: &[NA_F64, NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "which",
        class_filter: None,
        runtime: "js_bun_which",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "zstdDecompress",
        class_filter: None,
        runtime: "js_bun_zstd_decompress",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "zstdDecompressSync",
        class_filter: None,
        runtime: "js_bun_zstd_decompress_sync",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "gc",
        class_filter: None,
        runtime: "js_bun_gc",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "generateHeapSnapshot",
        class_filter: None,
        runtime: "js_bun_generate_heap_snapshot",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "file",
        class_filter: None,
        runtime: "js_bun_file",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "write",
        class_filter: None,
        // Returns an already-settled Promise as a NaN-boxed value (same
        // convention as the fs.promises thunks).
        runtime: "js_bun_write",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "Glob",
        class_filter: None,
        runtime: "js_bun_glob_new",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "unsupported",
        class_filter: None,
        runtime: "js_bun_unsupported",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // Module-level aliases with node:url semantics (issue table:
    // `import { pathToFileURL, fileURLToPath } from "bun"`).
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "pathToFileURL",
        class_filter: None,
        runtime: "js_url_path_to_file_url",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "bun",
        has_receiver: false,
        method: "fileURLToPath",
        class_filter: None,
        runtime: "js_url_file_url_to_path",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
];
