use super::*;

pub(super) const HTTP_SERVER_ROWS: &[NativeModSig] = &[
    // ========== node:http server (issue #577) ==========
    // Module-level: `import { createServer } from "node:http"; createServer(options?, handler?)`
    // Issue #2210 — accepts an optional 2nd `options` arg (Node 18.4+):
    //   `createServer({ headersTimeout, keepAliveTimeout, ... }, handler)`
    // Pass both user args as full NaN-boxed values: the runtime normalizes
    // handler-first and options-first overloads before storing options.
    NativeModSig {
        module: "http",
        has_receiver: false,
        method: "createServer",
        class_filter: None,
        runtime: "js_node_http_create_server_with_options",
        args: &[NA_F64, NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // `http.Server(handler)` is Node's callable-constructor alias for
    // `http.createServer` (works with or without `new`). #2132.
    // Same overloaded shape as `createServer` above (#2210).
    NativeModSig {
        module: "http",
        has_receiver: false,
        method: "Server",
        class_filter: None,
        runtime: "js_node_http_create_server_with_options",
        args: &[NA_F64, NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // HttpServer instance methods (class_filter: HttpServer)
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "listen",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_listen",
        // Node's `listen()` is variadic: listen(port[, host][, backlog][, cb]),
        // listen(options[, cb]), listen(cb). Positional NativeArgKinds can't
        // express "the callback floats to whichever position it's in", so pass
        // every user arg as a JS array and let the runtime resolve the overload
        // by value type (string→host, function→callback). Pre-#2041 the fixed
        // `[NA_F64, NA_PTR]` mis-routed a host string into the callback slot and
        // dropped the real callback. Issue #2041.
        //
        // #2129: returns the server handle (NR_PTR) so
        // `createServer(...).listen(...).on(...)` chains correctly. Pre-fix
        // this was NR_VOID and chained sites broke at runtime with
        // `undefined.on is not a function`.
        args: &[NA_VARARGS],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "close",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_close",
        args: &[NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "closeAllConnections",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_close_all_connections",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "closeIdleConnections",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_close_idle_connections",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "on",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    // `server.address()` — returns `{ port, address, family }` (or `null`
    // before listen completes). Runtime serializes to JSON; codegen
    // parses via `NR_OBJ_FROM_JSON_STR`. Without this row, `server.address()`
    // fell through to typed-feedback dispatch and returned NaN.
    // (#2153 followup to #2129.)
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "address",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_address_json",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_listening",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_listening_value",
        args: &[],
        ret: NR_F64,
    },
    // Issue #2210 — `server.<name>` timeout / socket-option accessors.
    // The HIR rewrites `server.headersTimeout` reads / writes to
    // `__get_headersTimeout` / `__set_headersTimeout` synthetic methods
    // when the receiver is tagged as `("http", "HttpServer")`; bare-name
    // fallback rows also wired so receivers that escape the HIR-rewrite
    // (e.g. assigned through a local before the property access) still
    // hit the FFI.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_headersTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_headersTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_headers_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_keepAliveTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_keepAliveTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_keep_alive_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_keepAliveTimeoutBuffer",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_keep_alive_timeout_buffer",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_keepAliveTimeoutBuffer",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_keep_alive_timeout_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_requestTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_requestTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_request_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_timeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_timeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_idle_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_maxHeadersCount",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_maxHeadersCount",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_max_headers_count",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_maxRequestsPerSocket",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_maxRequestsPerSocket",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_max_requests_per_socket",
        args: &[NA_F64],
        ret: NR_F64,
    },
    // Bare-name dispatch — same FFI, covers receivers that escape the
    // `__get_<name>` HIR rewrite (e.g. assigned through a local).
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "headersTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "listening",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_listening_value",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "keepAliveTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "keepAliveTimeoutBuffer",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_keep_alive_timeout_buffer",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "requestTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "timeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "maxHeadersCount",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "maxRequestsPerSocket",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    // `server.setTimeout(msecs, [callback])` — the canonical
    // EventEmitter-style setter mirrors `socket.setTimeout`. The
    // callback (if supplied) is registered as a `'timeout'` listener.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setTimeout",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_set_timeout_method",
        args: &[NA_F64, NA_PTR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // `server.ref()` / `server.unref()` — EventEmitter chainables that
    // return `this`. Without these rows they fell through to a generic
    // handler that yielded the receiver *handle* as a raw number, so
    // `createServer(cb).unref().listen(...)` broke with `(number).listen
    // is not a function` (#5011). Mirrors the `listen` NR_PTR fix (#2129):
    // the runtime returns the server handle so chaining works. `unref()`
    // also clears the loop-keepalive flag so the process can exit (Node
    // semantics); `ref()` restores it.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "ref",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_ref",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "unref",
        class_filter: Some("HttpServer"),
        runtime: "js_node_http_server_unref",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // IncomingMessage instance methods
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "on",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    // IncomingMessage events in the async-hooks provider probes are terminal
    // (`end`/`error`), so the shared registration path also provides the
    // observable one-shot behaviour while ensuring client responses are
    // cross-routed into perry-ext-http's listener registry.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "once",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_once",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "pause",
        class_filter: Some("IncomingMessage"),
        // #4975: `Readable.pause()` returns `this` — use the self-returning
        // wrapper + NR_PTR so `res.pause().on(...)` chains instead of
        // yielding `undefined`/a raw number.
        runtime: "js_node_http_im_pause_self",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "resume",
        class_filter: Some("IncomingMessage"),
        // #4975: `Readable.resume()` returns `this` so the canonical
        // `res.resume().on('end', …)` body-drain chain keeps flowing
        // (test-http-write-head-2). Was NR_VOID → the chain hit
        // `(number|undefined).on`.
        runtime: "js_node_http_im_resume_self",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "destroy",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_destroy",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "read",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_read",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setEncoding",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_set_encoding",
        args: &[NA_STR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setTimeout",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_set_timeout",
        args: &[NA_F64, NA_PTR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // ServerResponse instance methods
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_header_self",
        // #4826: value passed as a raw JSValue (NA_F64) so array values
        // (e.g. Set-Cookie) are detected and emitted as one wire line per
        // element instead of a single comma-joined / JSON-stringified line.
        args: &[NA_STR, NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "getHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_header",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "removeHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_remove_header",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "hasHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_has_header_value",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "getHeaders",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_headers_json",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "getHeaderNames",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_header_names_json",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "appendHeader",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_append_header",
        args: &[NA_STR, NA_STR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setHeaders",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_headers",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "writeHead",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write_head",
        // #2132: arg2/arg3 are raw JSValues so the runtime can disambiguate
        // the `writeHead(status, headers)` vs `writeHead(status, statusMessage,
        // headers)` overloads (string ⇒ statusMessage, object ⇒ headers) and
        // serialize the headers object. Previously typed `NA_STR`, which
        // coerced a headers *object* to `"[object Object]"` and silently
        // dropped every header passed via `writeHead`.
        args: &[NA_F64, NA_JSV, NA_JSV],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "write",
        class_filter: Some("ServerResponse"),
        // #4909: pass the trailing `(encoding?, callback?)` args as raw
        // JSValues so the runtime can fire the write callback and return a
        // real boolean (NR_F64 → NaN-boxed bool) for backpressure. The
        // previous `js_node_http_res_write` (NA_F64 only / NR_I32→undefined)
        // silently dropped the callback and returned `undefined`.
        runtime: "js_node_http_res_write_full",
        args: &[NA_F64, NA_JSV, NA_JSV],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addTrailers",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_add_trailers",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "end",
        class_filter: Some("ServerResponse"),
        // #4909: route to the callback-aware end so `res.end(chunk, cb)` /
        // `res.end(cb)` fire their callback (and the queued write callbacks)
        // before `'finish'`. arg2/arg3 carry the `(encoding?, callback?)` tail.
        runtime: "js_node_http_res_end_full",
        args: &[NA_F64, NA_JSV, NA_JSV],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "flushHeaders",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_flush_headers",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "cork",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_cork",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "uncork",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_uncork",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setTimeout",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_timeout",
        args: &[NA_F64, NA_PTR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "writeEarlyHints",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write_early_hints",
        args: &[NA_F64, NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "writeContinue",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write_continue",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "writeProcessing",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_write_processing",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "on",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    // Method-call aliases for property-style accessors. Until the
    // HIR-level PropertyGet→__get_<name> rewrite lands (followup),
    // user code must use the method-call form: `req.method()` (calls
    // js_node_http_im_method) instead of `req.method` (property
    // read). Same shape as fastify's `request.method()` / `request.url()`.
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "method",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_method",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "url",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_url",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "httpVersion",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_http_version",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "setStatus",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_status",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "getStatus",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_status",
        args: &[],
        ret: NR_F64,
    },
    // Property accessors as `__get_<name>` / `__set_<name>` synthetic methods
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_method",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_method",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_url",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_url",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_httpVersion",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_http_version",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_httpVersionMajor",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_http_version_major",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_httpVersionMinor",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_http_version_minor",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_complete",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_complete",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_aborted",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_aborted",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_destroyed",
        class_filter: Some("IncomingMessage"),
        runtime: "js_node_http_im_destroyed",
        args: &[],
        ret: NR_I32,
    },
    // Closes #769 followup — client-side `res.statusCode` /
    // `res.statusMessage` / `res.headers` after `http.request(url, cb)`.
    // The HIR registers the `res` arrow param as ("http",
    // "IncomingMessage"); these entries route the rewritten
    // `__get_<prop>` reads to perry-ext-http's accessor (the same
    // crate that owns the client-IncomingMessage registry the
    // response queue populates). (Restored after the #1099 squash-merge
    // dropped them via a conflict auto-resolution.)
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_statusCode",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_code",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_statusMessage",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_message",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_headers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_headers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_trailers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_trailers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_socket",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_connection",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_req",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_req",
        args: &[],
        ret: NR_F64,
    },
    // PR #1146 belt-and-braces: bare-name dispatch for the same three
    // client-IncomingMessage properties, for sites where the HIR rewrite
    // to `__get_<prop>` doesn't fire (receiver isn't statically tagged
    // as ("http", "IncomingMessage"), e.g. one assigned through a local
    // before the property read).
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "statusCode",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_code",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "statusMessage",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_status_message",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "headers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_headers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "trailers",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_response_trailers",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "socket",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "connection",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "req",
        class_filter: Some("IncomingMessage"),
        runtime: "js_http_incoming_message_req",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_statusCode",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_get_status",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_statusCode",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_status",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_statusMessage",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_status_message",
        args: &[NA_STR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_sendDate",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_send_date",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__set_strictContentLength",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_set_strict_content_length",
        args: &[NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_headersSent",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_headers_sent",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_writableEnded",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_writable_ended",
        args: &[],
        ret: NR_I32,
    },
    NativeModSig {
        module: "http",
        has_receiver: true,
        method: "__get_writableFinished",
        class_filter: Some("ServerResponse"),
        runtime: "js_node_http_res_writable_finished",
        args: &[],
        ret: NR_I32,
    },
    // ========== node:https server (issue #577 Phase 2) ==========
    NativeModSig {
        module: "https",
        has_receiver: false,
        method: "createServer",
        class_filter: None,
        runtime: "js_node_https_create_server",
        args: &[NA_F64, NA_PTR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // `https.Server(options, handler)` is Node's callable-constructor
    // alias for `https.createServer` (works with or without `new`). #2132.
    NativeModSig {
        module: "https",
        has_receiver: false,
        method: "Server",
        class_filter: None,
        runtime: "js_node_https_create_server",
        args: &[NA_F64, NA_PTR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "listen",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_listen",
        // Variadic listen() overloads — see the http `listen` row. Issue #2041.
        // Returns the server handle for chainability (#2129).
        args: &[NA_VARARGS],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "close",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_close",
        args: &[NA_PTR],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "on",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "addListener",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_on",
        args: &[NA_STR, NA_PTR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "address",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_address_json",
        args: &[],
        ret: NR_OBJ_FROM_JSON_STR,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_listening",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_listening_value",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "closeAllConnections",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_close_all_connections",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "closeIdleConnections",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_close_idle_connections",
        args: &[],
        ret: NR_VOID,
    },
    // `server.ref()` / `server.unref()` for the https server — return
    // `this` (NR_PTR) so chaining works, matching the http rows. #5011.
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "ref",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_ref",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "unref",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_unref",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_headersTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_headersTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_headers_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_keepAliveTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_keepAliveTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_keep_alive_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_keepAliveTimeoutBuffer",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_keep_alive_timeout_buffer",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_keepAliveTimeoutBuffer",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_keep_alive_timeout_buffer",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_requestTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_requestTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_request_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_timeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_timeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_idle_timeout",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_maxHeadersCount",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_maxHeadersCount",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_max_headers_count",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__get_maxRequestsPerSocket",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "__set_maxRequestsPerSocket",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_max_requests_per_socket",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "headersTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_headers_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "listening",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_listening_value",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "keepAliveTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_keep_alive_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "keepAliveTimeoutBuffer",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_keep_alive_timeout_buffer",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "requestTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_request_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "timeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_idle_timeout",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "maxHeadersCount",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_headers_count",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "maxRequestsPerSocket",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_max_requests_per_socket",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "https",
        has_receiver: true,
        method: "setTimeout",
        class_filter: Some("HttpsServer"),
        runtime: "js_node_https_server_set_timeout_method",
        args: &[NA_F64, NA_PTR],
        ret: NR_GCPTR.managed_common_handle(),
    },
];
