use super::*;

pub(super) const MEDIA_ROWS: &[NativeModSig] = &[
    // ========== sharp ==========
    // Factory: sharp(path) → js_sharp_from_file. Instance methods take
    // Handle (i64), compatible with the has_receiver:true dispatch path.
    // `sharp(input)` accepts a file-path string, a Buffer/Uint8Array of encoded
    // image bytes, or a `{ create: { ... } }` descriptor. Pass the raw
    // NaN-boxed value (NA_JSV) so `js_sharp_from_input` can branch on its
    // representation.
    NativeModSig {
        module: "sharp",
        has_receiver: false,
        method: "default",
        class_filter: None,
        runtime: "js_sharp_from_input",
        args: &[NA_JSV],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: false,
        method: "sharp",
        class_filter: None,
        runtime: "js_sharp_from_input",
        args: &[NA_JSV],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "resize",
        class_filter: None,
        runtime: "js_sharp_resize",
        args: &[NA_F64, NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "rotate",
        class_filter: None,
        runtime: "js_sharp_rotate",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "flip",
        class_filter: None,
        runtime: "js_sharp_flip",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "flop",
        class_filter: None,
        runtime: "js_sharp_flop",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "grayscale",
        class_filter: None,
        runtime: "js_sharp_grayscale",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "blur",
        class_filter: None,
        runtime: "js_sharp_blur",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "sharpen",
        class_filter: None,
        runtime: "js_sharp_sharpen",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // `.extract({ left, top, width, height })` — the options object is passed
    // as a NaN-boxed value (NA_F64 slot); `js_sharp_extract` reads its fields.
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "extract",
        class_filter: None,
        runtime: "js_sharp_extract",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "autoOrient",
        class_filter: None,
        runtime: "js_sharp_auto_orient",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // `.extend({ top, bottom, left, right, background })` — options object.
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "extend",
        class_filter: None,
        runtime: "js_sharp_extend",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "trim",
        class_filter: None,
        runtime: "js_sharp_trim",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    // `.composite([{ input, top, left }, …])` — array of layer objects, passed
    // as a NaN-boxed pointer (NA_F64 slot); `js_sharp_composite` walks it.
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "composite",
        class_filter: None,
        runtime: "js_sharp_composite",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "jpeg",
        class_filter: None,
        runtime: "js_sharp_jpeg",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "png",
        class_filter: None,
        runtime: "js_sharp_png",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "webp",
        class_filter: None,
        runtime: "js_sharp_webp",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "avif",
        class_filter: None,
        runtime: "js_sharp_avif",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "toFile",
        class_filter: None,
        runtime: "js_sharp_to_file",
        args: &[NA_STR],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "toBuffer",
        class_filter: None,
        runtime: "js_sharp_to_buffer",
        args: &[],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "metadata",
        class_filter: None,
        runtime: "js_sharp_metadata",
        args: &[],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "width",
        class_filter: None,
        runtime: "js_sharp_width",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "sharp",
        has_receiver: true,
        method: "height",
        class_filter: None,
        runtime: "js_sharp_height",
        args: &[],
        ret: NR_F64,
    },
    // ========== cheerio ==========
    // cheerio.load(html) → doc handle (NR_PTR). Instance methods take Handle (i64).
    NativeModSig {
        module: "cheerio",
        has_receiver: false,
        method: "load",
        class_filter: None,
        runtime: "js_cheerio_load",
        args: &[NA_STR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "select",
        class_filter: None,
        runtime: "js_cheerio_select",
        args: &[NA_STR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "text",
        class_filter: None,
        runtime: "js_cheerio_selection_text",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "html",
        class_filter: None,
        runtime: "js_cheerio_selection_html",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "attr",
        class_filter: None,
        runtime: "js_cheerio_selection_attr",
        args: &[NA_STR],
        ret: NR_STR,
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "length",
        class_filter: None,
        runtime: "js_cheerio_selection_length",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "first",
        class_filter: None,
        runtime: "js_cheerio_selection_first",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "last",
        class_filter: None,
        runtime: "js_cheerio_selection_last",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "eq",
        class_filter: None,
        runtime: "js_cheerio_selection_eq",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "find",
        class_filter: None,
        runtime: "js_cheerio_selection_find",
        args: &[NA_STR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "children",
        class_filter: None,
        runtime: "js_cheerio_selection_children",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "parent",
        class_filter: None,
        runtime: "js_cheerio_selection_parent",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cheerio",
        has_receiver: true,
        method: "hasClass",
        class_filter: None,
        runtime: "js_cheerio_selection_has_class",
        args: &[NA_STR],
        ret: NR_F64,
    },
    // ========== zlib ==========
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "gzipSync",
        class_filter: None,
        runtime: "js_zlib_gzip_sync",
        // #2935: data as raw NaN-box bits (i64) + options object (f64). The
        // codec extracts the buffer/string pointer itself; the options object
        // carries `{ level }`.
        args: &[NA_JSV, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "gunzipSync",
        class_filter: None,
        runtime: "js_zlib_gunzip_sync",
        // #2935: data as raw NaN-box bits so the codec unboxes the buffer
        // pointer itself (a Buffer/string both decompress correctly).
        args: &[NA_JSV],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "deflateSync",
        class_filter: None,
        runtime: "js_zlib_deflate_sync",
        // #2935: see gzipSync above.
        args: &[NA_JSV, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "inflateSync",
        class_filter: None,
        runtime: "js_zlib_inflate_sync",
        // #2935: see gunzipSync above.
        args: &[NA_JSV],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "gzip",
        class_filter: None,
        runtime: "js_zlib_gzip",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "gunzip",
        class_filter: None,
        runtime: "js_zlib_gunzip",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "deflate",
        class_filter: None,
        runtime: "js_zlib_deflate",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "inflate",
        class_filter: None,
        runtime: "js_zlib_inflate",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "deflateRaw",
        class_filter: None,
        runtime: "js_zlib_deflate_raw",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "inflateRaw",
        class_filter: None,
        runtime: "js_zlib_inflate_raw",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "unzip",
        class_filter: None,
        runtime: "js_zlib_unzip",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    // Raw deflate / inflate + auto-detect unzip + CRC32 one-shots. Round
    // out the sync codec coverage on top of #1843's Transform-stream layer.
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "deflateRawSync",
        class_filter: None,
        runtime: "js_zlib_deflate_raw_sync",
        args: &[NA_F64, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "inflateRawSync",
        class_filter: None,
        runtime: "js_zlib_inflate_raw_sync",
        args: &[NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "unzipSync",
        class_filter: None,
        runtime: "js_zlib_unzip_sync",
        args: &[NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "crc32",
        class_filter: None,
        runtime: "js_zlib_crc32",
        args: &[NA_F64, NA_F64],
        ret: NR_F64,
    },
    // `zlib.brotli{Compress,Decompress}Sync(data)` — one-shot Brotli via the
    // `brotli` crate (already a `compression`-feature dep). Pass data as raw
    // NaN-box bits so shared codec validation sees the original JS value.
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "brotliCompressSync",
        class_filter: None,
        runtime: "js_zlib_brotli_compress_sync",
        args: &[NA_JSV],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "brotliDecompressSync",
        class_filter: None,
        runtime: "js_zlib_brotli_decompress_sync",
        args: &[NA_JSV],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "brotliCompress",
        class_filter: None,
        runtime: "js_zlib_brotli_compress",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "brotliDecompress",
        class_filter: None,
        runtime: "js_zlib_brotli_decompress",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "zstdCompressSync",
        class_filter: None,
        runtime: "js_zlib_zstd_compress_sync",
        args: &[NA_F64, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "zstdDecompressSync",
        class_filter: None,
        runtime: "js_zlib_zstd_decompress_sync",
        args: &[NA_F64, NA_F64],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "zstdCompress",
        class_filter: None,
        runtime: "js_zlib_zstd_compress",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "zstdDecompress",
        class_filter: None,
        runtime: "js_zlib_zstd_decompress",
        args: &[NA_F64, NA_F64],
        ret: NR_VOID,
    },
    // zlib Transform-stream factories (#1843 cluster 1). Each returns an i64
    // stream handle (zlib small-handle range) NaN-boxed with POINTER_TAG; subsequent
    // `.write`/`.end`/`.on`/`.pipe`/`.flush`/`.close` lose their static type
    // and route through HANDLE_METHOD_DISPATCH → `dispatch_zlib_stream`
    // (crates/perry-stdlib/src/common/dispatch.rs). `options` is NaN-boxed f64.
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createGzip",
        class_filter: None,
        runtime: "js_zlib_create_gzip",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createGunzip",
        class_filter: None,
        runtime: "js_zlib_create_gunzip",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createDeflate",
        class_filter: None,
        runtime: "js_zlib_create_deflate",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createInflate",
        class_filter: None,
        runtime: "js_zlib_create_inflate",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createDeflateRaw",
        class_filter: None,
        runtime: "js_zlib_create_deflate_raw",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createInflateRaw",
        class_filter: None,
        runtime: "js_zlib_create_inflate_raw",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createUnzip",
        class_filter: None,
        runtime: "js_zlib_create_unzip",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createBrotliCompress",
        class_filter: None,
        runtime: "js_zlib_create_brotli_compress",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    // `zlib.createBrotliDecompress(options?)` — now a real Transform-stream
    // handle (previously a feature-check Buffer stub; axios's
    // `typeof createBrotliDecompress === 'function'` gate still passes).
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createBrotliDecompress",
        class_filter: None,
        runtime: "js_zlib_create_brotli_decompress",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createZstdCompress",
        class_filter: None,
        runtime: "js_zlib_create_zstd_compress",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    NativeModSig {
        module: "zlib",
        has_receiver: false,
        method: "createZstdDecompress",
        class_filter: None,
        runtime: "js_zlib_create_zstd_decompress",
        args: &[NA_F64],
        ret: NR_HANDLE_ID,
    },
    // ========== cron ==========
    // schedule() returns a Handle (i64) → NR_PTR. Instance methods take Handle (i64).
    // Callback arg uses NA_JSV (bitcast) to pass the full NaN-boxed closure i64.
    NativeModSig {
        module: "cron",
        has_receiver: false,
        method: "validate",
        class_filter: None,
        runtime: "js_cron_validate",
        args: &[NA_STR],
        ret: NR_F64,
    },
    // schedule's callback must be the raw ClosureHeader pointer (NA_PTR
    // unbox) — the cron tick invokes it via js_closure_call0 on the raw
    // pointer, so passing tagged NaN-box bits (the old NA_JSV) threw
    // "value is not a function" on the first fire. Latent until the
    // event loop actually drove js_cron_timer_tick.
    NativeModSig {
        module: "cron",
        has_receiver: false,
        method: "schedule",
        class_filter: None,
        runtime: "js_cron_schedule",
        args: &[NA_STR, NA_PTR],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "cron",
        has_receiver: false,
        method: "describe",
        class_filter: None,
        runtime: "js_cron_describe",
        args: &[NA_STR],
        ret: NR_STR,
    },
    NativeModSig {
        module: "cron",
        has_receiver: true,
        method: "start",
        class_filter: None,
        runtime: "js_cron_job_start",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "cron",
        has_receiver: true,
        method: "stop",
        class_filter: None,
        runtime: "js_cron_job_stop",
        args: &[],
        ret: NR_VOID,
    },
    NativeModSig {
        module: "cron",
        has_receiver: true,
        method: "isRunning",
        class_filter: None,
        runtime: "js_cron_job_is_running",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "cron",
        has_receiver: true,
        method: "nextDate",
        class_filter: None,
        runtime: "js_cron_next_date",
        args: &[],
        ret: NR_STR,
    },
];
