use super::*;

pub(super) const NET_CLASSES_STATE_ROWS: &[NativeModSig] = &[
    NativeModSig {
        module: "net",
        has_receiver: false,
        method: "BlockList",
        class_filter: None,
        runtime: "js_net_block_list_new",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "net",
        has_receiver: false,
        method: "SocketAddress",
        class_filter: None,
        runtime: "js_net_socket_address_new",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "net",
        has_receiver: false,
        method: "isBlockList",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_is_block_list",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: false,
        method: "parse",
        class_filter: Some("SocketAddress"),
        runtime: "js_net_socket_address_parse",
        args: &[NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "getTypeOfService",
        class_filter: Some("Socket"),
        runtime: "js_net_socket_get_type_of_service",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "setTypeOfService",
        class_filter: Some("Socket"),
        runtime: "js_net_socket_set_type_of_service",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "addAddress",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_add_address",
        args: &[NA_STR, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "addRange",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_add_range",
        args: &[NA_STR, NA_STR, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "addSubnet",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_add_subnet",
        args: &[NA_STR, NA_F64, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "check",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_check",
        args: &[NA_STR, NA_STR],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "toJSON",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_to_json",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "fromJSON",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_from_json",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "rules",
        class_filter: Some("BlockList"),
        runtime: "js_net_block_list_rules",
        args: &[],
        ret: NR_GCPTR,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "address",
        class_filter: Some("SocketAddress"),
        runtime: "js_net_socket_address_get_address",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "family",
        class_filter: Some("SocketAddress"),
        runtime: "js_net_socket_address_get_family",
        args: &[],
        ret: NR_STR,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "port",
        class_filter: Some("SocketAddress"),
        runtime: "js_net_socket_address_get_port",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "flowlabel",
        class_filter: Some("SocketAddress"),
        runtime: "js_net_socket_address_get_flowlabel",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "listening",
        class_filter: Some("Server"),
        runtime: "js_net_server_get_listening",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "maxConnections",
        class_filter: Some("Server"),
        runtime: "js_net_server_get_max_connections",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "dropMaxConnection",
        class_filter: Some("Server"),
        runtime: "js_net_server_get_drop_max_connection",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "__set_maxConnections",
        class_filter: Some("Server"),
        runtime: "js_net_server_set_max_connections",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "net",
        has_receiver: true,
        method: "__set_dropMaxConnection",
        class_filter: Some("Server"),
        runtime: "js_net_server_set_drop_max_connection",
        args: &[NA_F64],
        ret: NR_F64,
    },
];
