use super::*;

pub(super) const NODE_DOMAIN_ROWS: &[NativeModSig] = &[
    NativeModSig {
        module: "domain",
        has_receiver: false,
        method: "Domain",
        class_filter: None,
        runtime: "js_domain_create",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "domain",
        has_receiver: false,
        method: "createDomain",
        class_filter: None,
        runtime: "js_domain_create",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "domain",
        has_receiver: false,
        method: "create",
        class_filter: None,
        runtime: "js_domain_create",
        args: &[],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "on",
        class_filter: None,
        runtime: "js_domain_on",
        args: &[NA_STR, NA_JSV],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "addListener",
        class_filter: None,
        runtime: "js_domain_on",
        args: &[NA_STR, NA_JSV],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "emit",
        class_filter: None,
        runtime: "js_domain_emit",
        args: &[NA_STR, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "run",
        class_filter: None,
        runtime: "js_domain_run",
        args: &[NA_F64, NA_VARARGS],
        ret: NR_F64,
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "bind",
        class_filter: None,
        runtime: "js_domain_bind",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "intercept",
        class_filter: None,
        runtime: "js_domain_intercept",
        args: &[NA_F64],
        ret: NR_F64,
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "add",
        class_filter: None,
        runtime: "js_domain_add",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "remove",
        class_filter: None,
        runtime: "js_domain_remove",
        args: &[NA_F64],
        ret: NR_GCPTR.managed_common_handle(),
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "enter",
        class_filter: None,
        runtime: "js_domain_enter",
        args: &[],
        ret: NR_F64,
    },
    NativeModSig {
        module: "domain",
        has_receiver: true,
        method: "exit",
        class_filter: None,
        runtime: "js_domain_exit",
        args: &[],
        ret: NR_F64,
    },
];
